INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Firewall Ansible Role
repo_url: https://gitlab.com/nofusscomputing/projects/ansible/firewall
edit_uri: '/-/ide/project/nofusscomputing/projects/ansible/firewall/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Ansible:

    - projects/ansible/index.md

    - Collections:

      - projects/ansible/collection/index.md

      - Firewall:

        - projects/ansible/collection/firewall/index.md

        - Role - Firewall:

          - projects/ansible/collection/firewall/roles/firewall/index.md


- Operations: 

  - operations/index.md

- Contact Us: contact.md

