---

- name: IPTables Install
  ansible.builtin.include_tasks:
    file: iptables/install.yaml
    apply:
      tags:
        - always
  tags:
    - always
  when: >
    nfc_role_firewall_firewall_type | lower == 'iptables'
      and
    not firewall_installed | default(false)


- name: IPTables Configure
  ansible.builtin.include_tasks:
    file: iptables/configure.yaml
    apply:
      tags:
        - always
  tags:
    - always
  when: >
    not firewall_configured | default(false)
      and
    firewall_installed | default(false)


- name: IPTables Add Rules
  ansible.builtin.include_tasks:
    file: iptables/add_rules.yaml
    apply:
      tags:
        - always
  loop: "{{ nfc_role_firewall_additional_rules }}"
  loop_control:
    loop_var: chain
  vars:
    nfc_role_firewall_additional_rules:

      - name: custom
        chain: true
        table: INPUT
        comment: All Custom Rules in this table

      - name: custom                               # Example rule to allow all for chain 'ssh2'
        source:
          host: '0.0.0.0/0'
        dest:
          port: 22
        protocol: tcp
        policy: ACCEPT
        comment: Allow ssh
        when: true

      - name: kubernetes-embedded-etcd
        chain: true
        table: INPUT
        protocol: tcp
        dest:
          port:
            - '2379'
            - '2380'
        comment: etcd. Servers only

      - name: kubernetes-api
        chain: true
        table: INPUT
        protocol: tcp
        dest:
          port: '6443'
        comment: Kubernetes API access. All Cluster hosts and end users

      - name: kubernetes-calico-bgp
        chain: true
        table: INPUT
        protocol: tcp
        dest:
          port: '179'
        comment: Kubernetes Calico BGP. All Cluster hosts and end users

      - name: kubernetes-flannel-vxlan
        chain: true
        table: INPUT
        protocol: udp
        dest:
          port: '4789'
        comment: Flannel. All cluster hosts

      - name: kubernetes-kubelet-metrics
        chain: true
        table: INPUT
        protocol: tcp
        dest:
          port: '10250'
        comment: Kubernetes Metrics. All cluster hosts

      - name: kubernetes-flannel-wg-four
        chain: true
        table: INPUT
        protocol: udp
        dest:
          port: '51820'
        comment: Flannel Wiregaurd IPv4. All cluster hosts

      - name: kubernetes-flannel-wg-six
        chain: true
        table: INPUT
        protocol: udp
        dest:
          port: '51821'
        comment: Flannel Wiregaurd IPv6. All cluster hosts

      - name: kubernetes-calico-typha
        chain: true
        table: INPUT
        protocol: tcp
        dest:
          port: '5473'
        comment: Calico networking with Typha enabled. Typha agent hosts.

      - name: metallb-l2-tcp
        chain: true
        table: INPUT
        protocol: tcp
        dest:
          port: '7946'
        comment: MetalLB Gossip

      - name: metallb-l2-udp
        chain: true
        table: INPUT
        protocol: udp
        dest:
          port: '7946'
        comment: MetalLB Gossip
  when: >
    chain.when | default(true) | bool
      and
    firewall_installed | default(false)
      and
    firewall_configured | default(false)
