---

- name: IPTables Install
  ansible.builtin.include_tasks:
    file: iptables/install.yaml
    apply:
      tags:
        - always
  tags:
    - always
  when: >
    nfc_role_firewall_firewall_type | lower == 'iptables'
      and
    not firewall_installed | default(false)


- name: IPTables Configure
  ansible.builtin.include_tasks:
    file: iptables/configure.yaml
    apply:
      tags:
        - always
  tags:
    - always
  when: >
    not firewall_configured | default(false)
      and
    firewall_installed | default(false)


- name: IPTables Add Rules
  ansible.builtin.include_tasks:
    file: iptables/add_rules.yaml
    apply:
      tags:
        - always
  loop: "{{ nfc_role_firewall_additional_rules }}"
  loop_control:
    loop_var: chain
  when: >
    firewall_installed | default(false)
      and
    firewall_configured | default(false)
